@base_url = http://localhost

@port = 3000

@url = {{base_url}}:{{port}}

@user_api = {{url}}/manager

@admin_api = {{url}}/admin

@product_api  = {{url}}/product

@sumproduct_api = {{url}}/sumproduct

@bearerToken = Bearer {{login.response.body.token}}

@bearerTokenH = Bearer {{login.response.headers.token}}

GET {{user_api}}/getmanager HTTP/1.1
###

GET {{user_api}}/checktoken HTTP/1.1
Authorization: {{bearerTokenH}}
###

GET {{user_api}}/getmanager/2 HTTP/1.1
###
GET {{user_api}}/getmanagerbyusername HTTP/1.1
Content-Type: application/json

{
    "username": "sirapop1",
    "email": "siraphop5@gmail.com"
}

###

# @name login
POST {{user_api}}/login HTTP/1.1
Content-Type: application/json

{
    "username": "anuponga25",
    "password": "11111za"
}

###
POST {{user_api}}/register HTTP/1.1
Content-Type: application/json

{
    "name": "อนุพงศ์ สูตรเลข",
    "shop_name": "ร้านปันสุข",
    "username": "anuponga25",
    "password": "11111za",
    "email": "anuponga25@gmail.com",
    "phone": "0871123654"
}
###
PUT {{user_api}}/editmanager HTTP/1.1
Authorization: {{bearerToken}}
Content-Type: application/json

{
    "name": "อนุพงศ์ สูตรเลข",
    "shop_name": "ร้านแสนบาน",
    "password": "11111za",
    "email": "anupong@gmail.com",
    "phone": "0899999921"
}
###

DELETE  {{user_api}}/deletemanager/4 HTTP/1.1


// Admin
###
GET {{admin_api}}/getadmin HTTP/1.1
Authorization: {{bearerToken}}

###
GET {{admin_api}}/getadmin/2 HTTP/1.1
Authorization: {{bearerToken}}
###
GET {{admin_api}}/getadminbyname HTTP/1.1
Authorization: {{bearerToken}}
Content-Type: application/json

{
    "nameadmin": "admindew"
}

###
POST {{admin_api}}/registeradmin HTTP/1.1
Authorization: {{bearerToken}}
Content-Type: application/json

{
    "nameadmin": "adminpond",
    "phoneadmin": "0955786621",
    "emailadmin": "adminaek@gmail.com",
    "usernameadmin": "adminpond",
    "passwordadmin": "123456za"
}

###
POST {{admin_api}}/loginadmin HTTP/1.1
Content-Type: application/json

{
    "usernameadmin": "adminpond",
    "passwordadmin": "123456za"
}

###

PUT  {{admin_api}}/updateadmin/2 HTTP/1.1
Content-Type: application/json
Authorization: {{bearerToken}}

{
    "nameadmin": "แอดมินฟัง",
    "phoneadmin": "0955786865",
    "emailadmin": "adminaek@gmail.com",
    "usernameadmin": "adminaekza1",
    "passwordadmin": "111111za"
}

###
DELETE {{admin_api}}/deleteadmin/5 HTTP/1.1
Authorization: {{bearerToken}}


// Product
###
GET {{product_api}}/getproduct HTTP/1.1
Authorization: {{bearerToken}}

###
GET {{product_api}}/getproduct/1 HTTP/1.1
Authorization: {{bearerToken}}
###
GET {{product_api}}/getproductbyname HTTP/1.1
Authorization: {{bearerToken}}
Content-Type: application/json

{
    "nameproduct": "กะเพราหมูกรอบ"
}
###
POST {{product_api}}/register HTTP/1.1
Authorization: {{bearerToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="nameproduct"

กะเพราไก่ไข่ดาว1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="priceproduct"

60
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="demo.png"
Content-Type: image/png

< ./demo01.JPG
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###
PUT {{product_api}}/updateproduct/2 HTTP/1.1
Authorization: {{bearerToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="nameproduct"

กะเพราหมูกรอบ
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="priceproduct"

50
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="demo.png"
Content-Type: image/png

< ./demo02.JPG
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###
DELETE {{{{product_api}}}}/deleteproduct/3 HTTP/1.1
Authorization: {{bearerToken}}

/// SUM PRODUCT

###
GET {{sumproduct_api}}/sumproduct HTTP/1.1
Authorization: {{bearerToken}}
###
GET {{sumproduct_api}}/getproducttoday HTTP/1.1
Authorization: {{bearerToken}}
###
GET {{sumproduct_api}}/sumproducttoday HTTP/1.1
Authorization: {{bearerToken}}
###

GET {{sumproduct_api}}/sumproductyesterday HTTP/1.1
Authorization: {{bearerToken}}

###

GET {{sumproduct_api}}/getproductyesterday HTTP/1.1
Authorization: {{bearerToken}}
###
POST {{sumproduct_api}}/selectdate HTTP/1.1
Authorization: {{bearerToken}}
Content-Type: application/json

{
    "date": "2023-05-03"
}
###
POST {{sumproduct_api}}/getselectdate HTTP/1.1
Authorization: {{bearerToken}}
Content-Type: application/json

{
    "date": "2023-05-03"
}

###
POST {{sumproduct_api}}/selectdatebetweenday HTTP/1.1
Authorization: {{bearerToken}}
Content-Type: application/json

{
    "datestart": "2023-05-03",
    "datestop": "2023-05-05"
}
###
POST {{sumproduct_api}}/getselectdatebetweenday HTTP/1.1
Authorization: {{bearerToken}}
Content-Type: application/json

{
    "datestart": "2023-05-03",
    "datestop": "2023-05-05"
}
###
POST {{sumproduct_api}}/addsumproduct HTTP/1.1
Authorization: bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbnVwb25nYTI1IiwidXNlcm5hbWVhZG1pbiI6ImFkbWlucG9uZCIsIm5hbWVhZG1pbiI6ImFkbWlucG9uZCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4MzM0NzM0NCwiZXhwIjoxNjg5MzQ3MzQ0fQ.LoI-xQCNE2LHvCUebJETtf6lZebQUYo0SftMO8f3mYz_CNA9n5rw3R3DHY4GV52e-op56vun3N-O4yGmaIwV4eGBduEhZa7A0rHlmAMoPAsPObcON3lLOT_K5tTtXUMVixXTaKKqHijbhNRqFCZogRgO2JxWyjGVweXsnXiqEqdRkV6tlTa0etFJKMiKeB86pxgvdjClwyLbs2I4eD88dQ01HKx38DhmeryhDBR3ckDXp16UqcyGCIkY4ydIUWuNvm_xET2fi-QrWWfvZmav6EDvCfCO9yFwjDynBJmVRgtn02FqFtXfG3NCFiC-YBRNJdtmgt07znW5Gn4rRltJdg
Content-Type: application/json

{
    "manager": "anuponga25",
    "nameproduct": "แกงเขียวหวานไก่",
    "priceproduct": "60"
}
